### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by rkrupnek** [mccdaq/mcculw#1]
Running pip with Python 3.6.1, I get:

> Collecting mcculw
>   Using cached mcculw-0.9.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\ROBERT~1.KRU\AppData\Local\Temp\pip-build-3p64eldz\mcculw\setup.py", line 7, in <module>
>         from version import __version__
>     ModuleNotFoundError: No module named 'version'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\ROBERT~1.KRU\AppData\Local\Temp\pip-build-3p64eldz\mcculw\

Any ideas?

**Comment by dfraskamcc** [comment]
Please try running the "pip install mcculw" command again now. There was an issue introduced into setup.py for version 0.9.1 that would have prevented installation. The fix is up on PyPI, which should now be 0.9.2.

**Comment by rkrupnek** [comment]
It installed just fine now.  Looking forward to checking it out!  Thanks!
