### ISSUE TITLE
Unable to find code for input counter (CTR0) for USB-1808.

### ISSUE THREAD

**Issue by javierRomeroPower** [mccdaq/mcculw#11]
Unable to find code for input counter (CTR0) for USB-1808. Trying to measure period and pulse width.

**Comment by jeffreyg3** [comment]
There are 2 examples included in the UL for Python on Windows (MCCULW) you can use with counters 0&1 of the USB-1808 series.
UI (User Interface) example:  ULCT07.py
Console example: c_in.py
The function call is c_in_32 and is formatted like this:  value = ul.c_in_32(self.board_num, channel)
Prior to sending this email, I reconfirmed both these examples function (event counter mode) for counters 0 and 1 of the USB-1808s

**Comment by javierRomeroPower** [comment]
Hi Jeff,

Just to confirm, this is for CTR0 and CTR1 inputs? I found counter output
in library, which I do not use.

Thanks,

**Comment by jeffreyg3** [comment]
Yes, that is correct.
