### ISSUE TITLE
Raw Data Array

### ISSUE THREAD

**Issue by max-vdL** [mccdaq/mcculw#12]
Hello,
Example used: ULAIO1 (from ui)
I am trying to write data from an analog input into another file at 1000 Herz.
Right now my solution is using the variable eng_value to write. I tried finding out what the original array is where all the raw analog input data is being saved but cannot find it.
I know the a_in function is involved, but can't find where it draws the values from.

Thanks in advance, 
Max

**Comment by InfiniteWhite** [comment]
Thank you for your fast and helpful answer!
Next up I am trying to generate a column displaying a clock/timer (similiar to the count value, but relying on time). Is there a function in the Universal Library taking care of this? If threre was, I would be saving some time coding one myself.

**Comment by jeffreyg3** [comment]
Unfortunately there is no UL function for that.
