### ISSUE TITLE
Issues with mcculw import ul

### ISSUE THREAD

**Issue by JoseWired** [mccdaq/mcculw#17]
Hello;

I'm trying to run the example code using Python and the mcculw. The very first line

from mcculw import ul       throws an error which last line says " AtributeError: function 'cbAChanInputMode' not found. "   The PC has windows 7 Home Premium SP1 64 bits (Iddle 32 bits)

This same example runs OK in another PC with windows 7 Professional SP1 32bits. The board used is MCC USB-7202.

I need to know what am I doing wrong. Both systems have the same Python 3.7-32 bits and the same mcculw installed. I want the programs to run in any PC to implement test stations.

Any help will be appreciated.

**Comment by jeffreyg3** [comment]
Hi JoseWired, 

I'm taking a guess here to be sure, but the first thing I would look for is for multiple copies of cbw32.dll on your system.  Open your Windows File explorer, go to the root of C:\ drive, and search for cbw32.dll.  You should find one instance of that file, installed in C:\Program files (x86)\Measurement Computing\DAQ. (drop the (x86) if running on 32 bit Windows).
if you find more than one copy, delete any other not in the afore mentioned directory.

Best regards,

**Comment by JoseWired** [comment]
Hello jeffreyg3,

Thank you for your response.
I searched the cbw32.dll and it appears only once in C:\Program files(x86)\Measurement Computing\DAQ.
Instacal is working OK, The USB-7202 is listed and tested OK.

**Comment by JoseWired** [comment]
jeffreyg3:

I made something that worked:

I downloaded the 64 bit version of Python, then from its path I installed the mcculw.
When I wrote the sample exercise in Iddle(64bits), it worked fine!

I did that as a try/error, because I'm new in Python and mcculw.

Thanks !
