### ISSUE TITLE
mcculw.ul.ULError: Error 1 - Acquisition with DT9804 

### ISSUE THREAD

**Issue by ajmoralesa** [mccdaq/mcculw#18]
I am trying to test some of the examples provided using a DT9804-EC-I-BNC-8DI device, but all of them result in `mcculw.ul.ULError: Error 1: Invalid board number.`

All drivers are correctly installed as I am able to acquire signals using other software (e.g. QuickDAQ), although no board appears in the InstaCal app. 

What can be the issue?

Thanks for your support

**Comment by jeffreyg3** [comment]
Unfortunately, DT9804 series cannot be accessed with the MCC UL for Python (mcculw).  mcculw supports Measurement Computing devices only.  For the complete listing, I recommend you review the ULHELP available on line:  https://www.mccdaq.com/pdfs/manuals/Mcculw_WebHelp/ULStart.htm

There is no python support for the DT9804 series.  To see the supported list of software please see the data sheet: https://www.mccdaq.com/pdfs/specs/DT9800-EC-I-Datasheet.pdf 
page 3.

**Comment by ajmoralesa** [comment]
Thanks for the information.

Are there any plans to make DT900 series accesible through `mcculw`?

I just found [pyDTOL](https://github.com/jensb89/pyDTOL), which seems to cover this gap, although it does not seem to support python 3+.
