### ISSUE TITLE
mcculw cannot find the dlls on python 3.8

### ISSUE THREAD

**Issue by simonfagerholm** [mccdaq/mcculw#20]
"Could not find module 'cbw32.dll'. Try using the full path with constructor syntax."

Different version of Instacal makes no difference.
I have a Win10 64bit that works, but this is really annoying. Either the discovery should be better implemented or the Instacal installation changed.

I should not need to modify the package source or manually change the path on *some* computer.

FYI: 2 other tickets have been raised about this issue before, but closed without any action.

**Comment by BRV64** [comment]
Go to ul.py, line 33 to 39 and replace like this.

# Load the correct library based on the Python architecture in use
if struct.calcsize("P") == 4:
    _cbw = WinDLL('C:\\Program Files (x86)\\Measurement Computing\\DAQ\\cbw32.dll')
else:
    _cbw = WinDLL('C:\\Program Files (x86)\\Measurement Computing\\DAQ\\cbw64.dll')

_cbw.cbAChanInputMode.argtypes = [c_int, c_int, c_int]

**Comment by simonfagerholm** [comment]
> Go to ul.py, line 33 to 39 and replace like this.
> 
> # Load the correct library based on the Python architecture in use
> if struct.calcsize("P") == 4:
> _cbw = WinDLL('C:\Program Files (x86)\Measurement Computing\DAQ\cbw32.dll')
> else:
> _cbw = WinDLL('C:\Program Files (x86)\Measurement Computing\DAQ\cbw64.dll')
> 
> _cbw.cbAChanInputMode.argtypes = [c_int, c_int, c_int]

Like I said: 

> I should not need to modify the package source or manually change the path on some computer.

The problem is not how to solve it, the problem is that the module contains a bug that requires manual patching on each affected machine.
Imagine deploying this on a hundred machine, what a nightmare!

**Comment by astaruch** [comment]
I think that the usual way is to copy and register the final DLL into C:\Windows\System32.

I was trying to do that, but registration has failed
```
cp 'C:\Program Files (x86)\Measurement Computing\DAQ\cbw64.dll'
cd 'C:\Windows\System32
regsvr32.exe cbw64.dll
```
The module "cbw64.dll" was loaded but the entry-point DllRegisterServer was not found. 
Make sure that "cbw64.dll" is valid DLL or OCX file and then try again.

If this went OK, then there is no need for hacking the path. Python would be able to load it like other DLLs such as `ctypes.windll.kernel32` or `ctypes.windll.cbw64`.

**Comment by simonfagerholm** [comment]
@dfraskamcc @jperreault-mcc @jeffreyg3 Is this package even maintained? Is it possible to get any response from mcc?

**Comment by jeffreyg3** [comment]
Sorry for the lack of response.
As you know there is a workaround for now.
We are working on an update to our Windows python offering but that is still around a month out.
The update does include a fix for this issue.

**Comment by simonfagerholm** [comment]
@jeffreyg3 
Can you specify what workaround you are talking about?

**Comment by jeffreyg3** [comment]
Unfortunately I cannot.  Measurement Computing does not provide information on unreleased products.

**Comment by simonfagerholm** [comment]
@jeffreyg3 
You stated: 
> As you know there is a workaround for now.

My question was about that workaround. Either you can tell me what you refer to or I clearly cannot know about it.

**Comment by jperreault-mcc** [comment]
This issue was introduced in Python 3.8.  You can see the documentation at [https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew].  For now a good workaround without having to make changes to the mcculw source code would be to add the lines below to your code prior to importing the mcculw package.  When the new mcculw package is released, these lines can be removed.
`import os
os.add_dll_directory("C:\\Program Files (x86)\\Measurement Computing\\DAQ")`
Note: The install directory for the DLL may be different depending on your OS and/or installation settings.

**Comment by simonfagerholm** [comment]
@jperreault-mcc Great answer! I was incorrectly suspecting the differences in the 32/64-bit versions.
I have confirmed that it only occur on python 3.8 32- and 64-bit version, but not on python 3.7 32- and 64-bit. I have updated the header with this information.
Instacal-installation seems to add a record to PATH, so a way to get the same behavior in python 3.7 and 3.8 is to add the following __before__ import of `mcculw`:
```python
import os
if hasattr(os, 'add_dll_directory'):
    # Must add dll folders manually in python 3.8
    for path in os.environ['PATH'].split(';'):
        if os.path.exists(path):
            os.add_dll_directory(path)
```
__Remember that adding this can cause unsecure code to be executed if a dll:s are overridden in PATH.__
