### ISSUE TITLE
Error 126: Cannot find CB.CFG file

### ISSUE THREAD

**Issue by BRV64** [mccdaq/mcculw#21]
I try to run this code on : https://github.com/mccdaq/mcculw
But it sends me this error.
Can somebody tell me what's wrong or provide the file?

>>> value = ul.a_in(board_num, channel, ai_range)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ROBOT\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcculw\ul.py", line 84, in a_in
    _check_err(_cbw.cbAIn(
  File "C:\Users\ROBOT\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcculw\ul.py", line 5877, in _check_err
    raise ULError(errcode)
mcculw.ul.ULError: Error 126: Cannot find CB.CFG file.

**Comment by BRV64** [comment]
I had to grab the file from 
C:\ProgramData\Measurement Computing\DAQ
Uninstall InstaCal
Install it again
Restart
Put the file back into the folder

**Comment by jeffreyg3** [comment]
I have been in communication with BRV64 regarding this matter.  Turns out he just needed to run InstaCal with his USB-TC attached so he could generate the missing CB.CFG file.  he is up and running now.

**Comment by donBriner** [comment]
I'm having the same issue.  I had the USB-DT9816 plugged in, and verified working with the QuickDAQ software, then unistalled InstaCal and reinstalled.  Still no sign of CB.CFG anywhere.

Any help would be appreciated.  Thanks.

**Comment by FaSoa** [comment]
Data Translation's DT9816 is not supported under MCC's Universal Library software.  With the DT9816, the supported software options to use are DT Open Layers API, QuickDAQ, LV-Link3 for LabVIEW, DASYLab, and MATLAB.
