### ISSUE TITLE
Acqknowledge does not detect digital signal

### ISSUE THREAD

**Issue by Juny0ung** [mccdaq/mcculw#25]
I'm trying to send digital signal from "Psychopy" to "Acqknowledge", to check timing.
Before implementing, I checked if example codes worked well.
I used "USB-1280FS-Plus" module with "InstaCal". When I run examples, there was no error. It showed me message such as "Setting FIRSTPORTA to 255" and "Setting FIRSTPORTA bit 0 to 0" in digital_out.py example. However, in acqknowledge, nothing happened. 
I'm using MP150 and STP100C to receive digital signal. "USB-1280FS-PLUS" module is connected with STP100C by printer port. 5V, GND, A0 port, B0 port is connected to printer port.
I could check digital channel 8 and 15 are connected because only they are read as 0V. But their values never changed to 5 (high) whatever I run the example or not.

I thought that A0 port and B0 port in "USB-1280FS-PLUS" are corresponded to 8 and 15 channel in Acqknowledge. So When I run the example code, at least one value of those channels (8, 15) should be changed since I got "Setting FIRSTPORTA to 255" message back.

I'm wondering what is the problem and can I solve the problem by fixing the code, or is it the hardware problem.
Thank you in advance.

* Examples which I run to check it was worked are as follows: digital_out.py, v_out.py, ULDO01.py, ULDO02.py, and VOut01.py

**Comment by jeffreyg3** [comment]
Hello Juny0ung, github is not the correct venue for your question as it has little to do with the MCC Windows Universal Library for Python, but more to do with your application of the hardware.  if you would like to pursue assistance on this matter, please submit your question directly to https://www.mccdaq.com/support/support_form.aspx

**Comment by Juny0ung** [comment]
I see
Thank you for information

**Comment by Juny0ung** [comment]
Hello Jeff
Since I do not get the answer from mccdaq and I may think I found out the reason why it didn't work which is directly using the library, I want to ask a question once more. Tell me if you can help me with.

I found out that connection from laptop to MP150 worked well which means that the problem was only because of my code. I installed mcculw by following instruction. Using pip command to install it, I got complete message,
"Requirement already satisfied: mcculw in c:\users\memcoglaptop6win\appdata\roaming\python\python36\site-packages (1.0.0)"
So I runned the example code and my code but I could check that none of sending and receiving is happened with my Psychopy code. What I'm curious is that after pip mcculw installing, is there anything for me to do additionally? I added mcculw downloaded path to Preferences in Psychopy due to this page.
https://www.psychopy.org/recipes/addCustomModules.html#addmodules

Thank you in advance. If this is also the problem that you can't help, sorry for bothering you with these kinds of problems.

**Comment by jeffreyg3** [comment]
Dear M. Juny0ung (sorry I don’t have your real name),
Thank you for contacting us.
I/we never received an email from you sent in to https://www.mccdaq.com/support/support_form.aspx as I suggested you do.
Let me start by stating I have no experience with Psychopy and I have no idea what an MP150 is. Nor should I as they are not products we support.
A question for you, what MCC hardware are you using?
From below, “…is that after pip mcculw installing, is there anything for me to do additionally?” You would have had to install InstaCal and attached your MCC data acquisition device (again, what device are you using?).  Depending upon the app, you may have to also run Instacal (after installing it and attaching your MCC device) so the device is added to the configuration.
I am running the Windows version of Pycharm Community edition 2020.2.3
I ran pip from a terminal, but I was in the folder where I recently installed python 3.9:
C:\Users\jgreenbe\AppData\Local\Programs\Python\Python39.
In the past I performed the same using pip for python38-32 and python37-32.
It’s just a suggestion, but perhaps you should contact the folks at Psychopy.org
Also, I recommend you restrict yourself to getting the mcculw library to operate with an MCC supported device using IDLE (included with most python installations on Windows).  That will confirm you have mcculw installed correctly for Python.  You can also run the examples from the terminal by entering at the commandprompt: python ./digital_out.py (for example).
Note if you get the “ModuleNotFoundError: no module named ‘mcculw’  “ error  when you run an example from the directory “C:\Users\Public\Documents\Measurement Computing\DAQ\Python\examples\console>”
Then here would be a place for you to enter: “pip install mcculw” from the same terminal.
Need a updated version of our drivers and free software? You can download a free upgrade of the MCCDAQ software (to version 6.72) from our site: mccdaq.exe<https://urldefense.com/v3/__https:/nam03.safelinks.protection.outlook.com/?url=https*3A*2F*2Furldefense.com*2Fv3*2F__https*3A*2Fnam03.safelinks.protection.outlook.com*2F*3Furl*3Dhttps*3A*2F*2Furldefense.com*2Fv3*2F__https*3A*2Fnam03.safelinks.protection.outlook.com*2F*3Furl*3Dhttps*3A*2F*2Furldefense.com*2Fv3*2F__https*3A*2Fnam03.safelinks.protection.outlook.com*2F*3Furl*3Dhttp*3A*2F*2Fwww.mccdaq.com*2Fdownloads*2FMCCDaqCD*2Fmccdaq.exe*26data*3D02*7C01*7CDaniele*40IBEX.ONE*7Cc7fc525df2bb4e665b5508d7b55974b4*7Cb4815476297140ff934ccae656660405*7C0*7C1*7C637177268138702800*26sdata*3Ds4nJjSAUrGWdNTXtOUfopCTr48oIiDHH6Wp38gbpkow*3D*26reserved*3D0__*3BJSUlJSUlJSUlJSUlJSUl!!FbZ0ZwI3Qg!8c37Q8Zd3CWC3TvM1yrIc6EsW80r0tf2ZqUQAAmPiFQDFT6OtlUqknbznBVp8-zWKvHwQQ*24*26data*3D02*7C01*7CDaniele*40IBEX.ONE*7Cc1e3c3a2894b4c29542f08d7b606e50e*7Cb4815476297140ff934ccae656660405*7C0*7C1*7C637178013057789650*26sdata*3D*2FqcO7n*2BxHrs2b3a*2FClLVD06dNL8tjXK3*2BPGK62F1LQU*3D*26reserved*3D0__*3BJSUlJSUlJSUlJSoqKioqKiUlKioqKioqKiolJSolJSUlJSUlJSUlJSUlJSUlJQ!!FbZ0ZwI3Qg!8x2H45k5kia0C1jgqlVxaLTOC-Z_eI47XZvwLbDVBRaQuqWH7I4Tvcmlh4hoJc4BZFoDnQ*24*26data*3D02*7C01*7CDaniele*40IBEX.ONE*7C8811c4d1122e4383a90808d7b649bb66*7Cb4815476297140ff934ccae656660405*7C0*7C0*7C637178300124184031*26sdata*3Di4E0MyD3ZofC9DHmnIKim1AxzzUm36tMl*2FtRMB*2ByaFQ*3D*26reserved*3D0__*3BJSUlJSUlJSUlJSoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiUlKioqKioqKiolJSoqKioqJSUlJSUlJSUlJSUlJSUl!!FbZ0ZwI3Qg!8ZTjopF6U2zCBly4soPEZqYDiJX4st9XgnRhr2i2lPP5Sk_90xXDIQe2DKreQLFFWg2E1g*24&data=02*7C01*7CDaniele*40IBEX.ONE*7C4d6c1ab367834bbcc77508d7b6fbd350*7Cb4815476297140ff934ccae656660405*7C0*7C1*7C637179065023798727&sdata=ekea3fP0HTOVP72gsPiVBJspxjbjRzHPWpX5TH4Qf3o*3D&reserved=0__;JSUlJSUlJSUlJSoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiolJSoqKioqKioqJSUqKiolJSUlJSUlJSUlJSUl!!FbZ0ZwI3Qg!8akHyFVY1QDc1noAwo0Xdc5CIDqfCQDn5zxf3eTsFOt5EkllZOLILw2kqTTN3nr2kolPVg$>


Thank you
Jeff Greenberg
Application Engineer

[cid:image001.png@01D6C706.00F2ED60]
Measurement Computing
10 Commerce Way
Norton, MA 02766
P: (508) 946-5100 Opt 2
F: (508) 946-9500
http://www.mccdaq.com/<https://urldefense.com/v3/__https:/nam03.safelinks.protection.outlook.com/?url=https*3A*2F*2Furldefense.com*2Fv3*2F__https*3A*2Fnam03.safelinks.protection.outlook.com*2F*3Furl*3Dhttps*3A*2F*2Furldefense.com*2Fv3*2F__https*3A*2Fnam03.safelinks.protection.outlook.com*2F*3Furl*3Dhttps*3A*2F*2Furldefense.com*2Fv3*2F__https*3A*2Fnam03.safelinks.protection.outlook.com*2F*3Furl*3Dhttp*3A*2F*2Fwww.mccdaq.com*2F*26data*3D02*7C01*7CDaniele*40IBEX.ONE*7Cc7fc525df2bb4e665b5508d7b55974b4*7Cb4815476297140ff934ccae656660405*7C0*7C1*7C637177268138712794*26sdata*3DyQKdgKogESg1kz4THpTRYxmonzWY3D2bDcsph35N2so*3D*26reserved*3D0__*3BJSUlJSUlJSUlJSUlJQ!!FbZ0ZwI3Qg!8c37Q8Zd3CWC3TvM1yrIc6EsW80r0tf2ZqUQAAmPiFQDFT6OtlUqknbznBVp8-zRDhYCJw*24*26data*3D02*7C01*7CDaniele*40IBEX.ONE*7Cc1e3c3a2894b4c29542f08d7b606e50e*7Cb4815476297140ff934ccae656660405*7C0*7C0*7C637178013057799645*26sdata*3DLxNiNHkXF9B16xqHN*2BnncpQoziUSsXqAkZrtdOU54xs*3D*26reserved*3D0__*3BJSUlJSUlJSUlJSoqKiolJSoqKioqKioqJSUqJSUlJSUlJSUlJSUlJSU!!FbZ0ZwI3Qg!8x2H45k5kia0C1jgqlVxaLTOC-Z_eI47XZvwLbDVBRaQuqWH7I4Tvcmlh4hoJc6URdcifA*24*26data*3D02*7C01*7CDaniele*40IBEX.ONE*7C8811c4d1122e4383a90808d7b649bb66*7Cb4815476297140ff934ccae656660405*7C0*7C1*7C637178300124193982*26sdata*3DRiCqZUOPKcw72vRhXGj*2Bt7Eif00OlRR0bU3UmkJXuqU*3D*26reserved*3D0__*3BJSUlJSUlJSUlJSoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiolJSoqKioqKioqJSUqKiUlJSUlJSUlJSUlJSUl!!FbZ0ZwI3Qg!8ZTjopF6U2zCBly4soPEZqYDiJX4st9XgnRhr2i2lPP5Sk_90xXDIQe2DKreQLE_qQxOIA*24&data=02*7C01*7CDaniele*40IBEX.ONE*7C4d6c1ab367834bbcc77508d7b6fbd350*7Cb4815476297140ff934ccae656660405*7C0*7C1*7C637179065023808696&sdata=CUUx2t5*2FyN2*2FwzleLLTvcx*2BlBop3ABhJOTJdb6lUWfY*3D&reserved=0__;JSUlJSUlJSUlJSoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqJSUqKioqKioqKiUlKiolJSUlJSUlJSUlJSUlJSUl!!FbZ0ZwI3Qg!8akHyFVY1QDc1noAwo0Xdc5CIDqfCQDn5zxf3eTsFOt5EkllZOLILw2kqTTN3nog3zqjvg$>
For new post-sales issues, please email info.email@mccdaq.com<mailto:info.email@mccdaq.com>. In each case a case number will be assigned, and the email will be forwarded to an Application Engineer. Please reference the case# in future correspondence pertaining to the same topic.
For new pre-sales questions, please email info.email@mccdaq.com<mailto:info.email@mccdaq.com>. Your questions will be answered by one of our Sales Engineers.
