### ISSUE TITLE
USB interface crashes (USB-ERB24)

### ISSUE THREAD

**Issue by plinwood** [mccdaq/mcculw#27]
I am using the mcculw library to switch a power source to a row of outputs with the "USB-ERB24" relais board.
The script is based on the "digital_out.py" example and simply switches the power source from relais 1 to relais 6.
This works for about 2 cycles and then the "USB-ERB24" disconnects from the windows machine. The onboard LED "USB" turns off and the device is not recognized by the windows machine anymore. Only a power cycle of the "USB-ERB24" brings it back again.

I get a range of errors:
First error is "Error 2: Digital device is not responding."
Then on the retries I get "Error 1: Invalid board number."
After couple of retries the interface finally crashes and I get "Error: The DAQ device does not support digital I/O"

Any ideas what the problem might be? 

Edit:
I've implemented a wait between calling ul.d_bit_out(). Seems to run way more stable now. Still get occasional "Error 1: Invalid board number" though. No idea where that comes from.
Is there communication timing implemented in the library?
Is there a way to check if the device is busy?

**Comment by unmanagedtn** [comment]
voltage transients if these are mechanical relays, try adding some snubber diodes...
