### ISSUE TITLE
Changing analog output 1 affects analog output 0

### ISSUE THREAD

**Issue by RaphaelBaettig** [mccdaq/mcculw#30]
I'm trying to set the two analog output channels of a USB-231 using the function "a_out" from the mcculw library for python.
Calling this function with the parameter "channel" set to 1 sets the output channel "AOut1" to the desired value, as expected. At the same time, the output channel "AOut0" also changes.  I've observed, that it has been set to -10V.
On the other hand, changing the value of "AOut0" does not seem to have any effect on "AOut1". 
I was able to reproduce this behavior using the example program ULAO01.py

I think, this behavior is not like it's supposed to be. Or did i overlook anything?

**Comment by jeffreyg3** [comment]
I think there is something amiss with your script.
Here is an example for the USB-231 (note must be assigned as board 0 in InstaCal)
it writes to  the DACs one at a time;  AOut0 and then AOut1.  Then clears them both back to 0V at termination.

[a_out.zip](https://github.com/mccdaq/mcculw/files/7033120/a_out.zip)

**Comment by RaphaelBaettig** [comment]
Hi Jeffrey
Thanks for your reply. Your example is actually working properly.
However, when searching the issue in my code, I found that executing "ao_range = ao_info.supported_ranges[0]" between writing to AOut0 and AOut1 seems to be causing the problem.

I was able to reproduce this behavior by slightly modifying your example code.
[a_out_modified.zip](https://github.com/mccdaq/mcculw/files/7037275/a_out_modified.zip)

**Comment by jeffreyg3** [comment]
From the documentation in the ao_info.py source code file:

    "NOTE: This class is primarily used to provide hardware information for the
    library examples and may change some hardware configuration values. It is
    recommended that values provided by this class be hard-coded in production
    code."
