### ISSUE TITLE
Sync Analog Output on Multiple Channels for USB-3114

### ISSUE THREAD

**Issue by 5igno** [mccdaq/mcculw#31]
Hello everyone,

I recently purchased a [USB-3114](https://www.mccdaq.com/usb-data-acquisition/USB-3100-Series.aspx) board and I am planning to use the synchronized analog output capability in a setup.

I am running on a Python 3.9.5 installed via Miniconda on WIndows 10. I installed  [the Universal Library for Windows library via pip](https://github.com/mccdaq/mcculw#installation).

According to the [documentation](https://www.mccdaq.de/PDFs/Manuals/Mcculw_WebHelp/ULStart.htm), the the USB 3114 should support this feature calling [a_out_scan](https://github.com/mccdaq/mcculw/blob/d5d4a3eebaace9544a356a1243963c7af5f8ca53/mcculw/ul.py#L485).
I [modified the a_out_scan example](https://github.com/5igno/mcculw/commit/bb05368775a30b092e0fb9dccfbd25de87a5b982) to demonstrate the ability to output different voltages on the 16 different channels.
The desired output is the one shown by the program ouput:

```
Found 1 DAQ device(s):
  USB-3114 (1D6B589) - Device ID = 164

Active DAQ device: USB-3114 (1D6B589)

Channel 0 Output Signal: 5.01
Channel 1 Output Signal: 5.02
Channel 2 Output Signal: 5.03
Channel 3 Output Signal: 5.04
Channel 4 Output Signal: 5.05
Channel 5 Output Signal: 5.06
Channel 6 Output Signal: 5.07
Channel 7 Output Signal: 5.08
Channel 8 Output Signal: 5.09
Channel 9 Output Signal: 5.10
Channel 10 Output Signal: 5.11
Channel 11 Output Signal: 5.12
Channel 12 Output Signal: 5.13
Channel 13 Output Signal: 5.14
Channel 14 Output Signal: 5.15
Channel 15 Output Signal: 5.16

Waiting for output scan to complete....
Scan completed **successfully**
````

Unfortunately, the output value is not updated in the voltage of the channels. Can you tell where the mistake is?

I also tried to use the single-channel function call [a_out](https://github.com/mccdaq/mcculw/blob/d5d4a3eebaace9544a356a1243963c7af5f8ca53/mcculw/ul.py#L458) to control each channel in a loop. Unfortunately, this function call updates the value of the next channel and at the same time returs the voltage of the previous channel to zero. This makes its use to control multiple channels not viable.

Would appreciate any support in the development of this capability.
Thank you for your help: much appreciated.
Kind regards,

Giorgio

**Comment by jeffreyg3** [comment]
Please see the attached example.
It is written to output a value of 1V on ch0, 2V on ch1 and so on, up to channel 4, using a_out_scan().

[3100_a_out_scan.zip](https://github.com/mccdaq/mcculw/files/7107865/3100_a_out_scan.zip)
