### ISSUE TITLE
USB-1808 not detected on Win11

### ISSUE THREAD

**Issue by russh26** [mccdaq/mcculw#32]
My MCC device (USB-1808) is not detected using either the instacal or the mcculw function: ul.get_daq_device_inventory(InterfaceType.ANY). I'm using the usb cable that came with the device, with not USB adapters, and I have tried multiple USB ports. I have tried running the same python scripts, in the same conda environment on two different computers. The computer running Windows 10 works perfectly. The computer running Windows 11, does not detect.

I know Win11 is fairly new and these issues are bound to happen (thus the reason my work laptop is still running Win10), but is there any work around? Or is there any timeline to integrating Win11. 

Note: I'm reporting this as an Issue because I haven't seen anywhere in the documentation that specifies Win11 non-compatibility.

Thanks

**Comment by jeffreyg3** [comment]
Hello,
This issue has been resolved with the release of mccdaq.exe 6.73, available on our website:[https://www.mccdaq.com/downloads/MCCDaqCD/mccdaq.exe](url)
