### ISSUE TITLE
Abort/cancel analog trigger

### ISSUE THREAD

**Issue by sTywin** [mccdaq/mcculw#8]
If one configures an analog trigger, e.g. `a_trig(board_num, channel, TrigType.TRIG_ABOVE, trig_value, ULRange.BIP10VOLTS)`, is there any way to cancel or abort the call if the trigger event does not take place?

**Comment by jeffreyg3** [comment]
Hello sTywin,
The only way to abort or cancel a_trig is to end the application.  There is no key or key combination that will allow you to move to the next line in your app.

a_trig is a tight loop of a_in and a comparison to the set value (trig_value), and repeats until the condition is satisfied, running as fast as your system will let it.

you might be better off writing this loop yourself, and place an application.DoEvents() (part of the VS CLR) in the code so you can cancel out of it if/when you need.
-Jeff

**Comment by sTywin** [comment]
Thanks, Jeff; I wasn't sure if `a_trig` was using something in the UL drivers or on the device itself to send the trigger signal. It sounds like implementing the comparison myself is the right way for me.

Cheers,
-Scott
